@startuml

title __GALAXYBANK-ATM's Class Diagram__\n

  namespace com.galaxybank {
    class com.galaxybank.AtmApplication {
    }
  }
  

  namespace com.galaxybank {
    namespace config {
      class com.galaxybank.config.ApplicationConfiguration {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace controller {
      class com.galaxybank.controller.CustomerServiceController {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      class com.galaxybank.model.ATM {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      class com.galaxybank.model.Account {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      enum AccountType {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      class com.galaxybank.model.Bank {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      class com.galaxybank.model.Card {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      class com.galaxybank.model.Customer {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      class com.galaxybank.model.Transaction {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace model {
      enum TransactionType {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace repository {
      interface com.galaxybank.repository.AccountRepository {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace repository {
      interface com.galaxybank.repository.AtmRepository {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace repository {
      interface com.galaxybank.repository.CardRepository {
      }
    }
  }
  

  namespace com.galaxybank {
    namespace service {
      class com.galaxybank.service.CustomerService {
      }
    }
  }
  

  com.galaxybank.controller.CustomerServiceController o-- com.galaxybank.service.CustomerService : customerService
  com.galaxybank.model.ATM o-- com.galaxybank.model.Bank : bank
  com.galaxybank.model.Account o-- com.galaxybank.model.AccountType : accountType
  com.galaxybank.model.Account o-- com.galaxybank.model.Customer : customer
  com.galaxybank.model.Card o-- com.galaxybank.model.Account : account
  com.galaxybank.model.Customer o-- com.galaxybank.model.Bank : bank
  com.galaxybank.model.Transaction o-- com.galaxybank.model.ATM : atm
  com.galaxybank.model.Transaction o-- com.galaxybank.model.Card : card
  com.galaxybank.model.Transaction o-- com.galaxybank.model.TransactionType : transactionType
  com.galaxybank.service.CustomerService o-- com.galaxybank.repository.AccountRepository : accountRepository
  com.galaxybank.service.CustomerService o-- com.galaxybank.repository.AtmRepository : atmRepository
  com.galaxybank.service.CustomerService o-- com.galaxybank.repository.CardRepository : cardRepository


right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
