@startuml

title __CONFIG's Class Diagram__\n

  namespace com.galaxybank {
    namespace config {
      class com.galaxybank.config.ApplicationConfiguration {
          + corsConfigurer()
      }
    }
  }

@enduml
