@startuml

title __GalaxyBank Controllers's Class Diagram__\n

  namespace com.galaxybank.controller {
      class com.galaxybank.controller.CustomerServiceController {
          + admin()
          + galaxybankatm()
          + getAtmInfo()
          + loginAdmin()
          + saveTransaction()
          + updateAtmBalance()
          + validateCardWithPin()
          - getJson()
      }
  }
  

  com.galaxybank.controller.CustomerServiceController o-- com.galaxybank.service.AdminService : adminService
  com.galaxybank.controller.CustomerServiceController o-- com.galaxybank.service.CustomerService : customerService


@enduml
